spring.application.name=projeto_pet

# =============================================
# Datasource - Oracle FIAP
# =============================================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm561365
spring.datasource.password=241006
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =============================================
# JPA / Hibernate - Oracle
# =============================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
